name: Deploy React Site


on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install # เปลี่ยนมาใช้ install เพื่อความยืดหยุ่นหากไม่มี lockfile

      - name: Build
        run: npm run build
        env:
          CI: false # สั่งปิดการเช็ก Warning เพื่อไม่ให้ระบบเตะโค้ดเราลงเมื่อเจอแจ้งเตือนเล็กน้อย

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # หากใช้ Create React App ให้เปลี่ยนคำว่า dist เป็น build ครับ

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
